# SITE CONFIGURATION
title: Brainhack 2024 Magdeburg # your site title
author: Brainhack 2024 Magdeburg # You :P
description: > # Meta description of Homepage
  Website of the Brainhack Magdeburg organization.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brainhackmagdeburg.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# THEME SETTINGS
navigation: # Navigation links
  # - {name: 'Home', link: '/'}
  - { name: "Schedule", link: "/schedule" }
  - { name: "Tutorials", link: "/tutorials" }
  - { name: "Social Events", link: "/social-events" }
  - { name: "About", link: "/about" }
  - { name: "Contact", link: "/contact" }

# tagline: >
#   Online edition: December 7th - 8th

hero_img: posts/BHM24_Flyer_small-4.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: brainhack2024.magdeburg@gmail.com # email for form submission

#twitter_username:  # replace with your_twitter_username or comment to remove link from footer
github_username: brainhackmagdeburg/brainhackmagdeburg.github.io # replace with your_github_username or comment to remove link from footer
mattermost_channel: bhg-magdeburg # replace with your_instagram_username or comment to remove link from footer

# google_tag_manager: GTM-NT2CFFQ # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

# service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ["_pages"]
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
